language: node_js

node_js:
  - '14.17.4'

jobs:
  include:
    - os: windows
      language: node_js
      node_js: "node"
    - os: linux
      dist: xenial
      services:
        - xvfb
      language: node_js
      node_js: "node"
      before_install:
        - sudo apt-get install -y rpm
    - os: osx
      language: node_js
      node_js: "node"

script:
- |
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      npm test
    fi;
    npm run build